"""
ET-Agent Inference Engine — vLLM-style paged KV Cache decode loop.

Completely replaces model.generate():
  1. Our own scheduler selects sequences
  2. Our KVBlockAllocator manages real CUDA tensor blocks
  3. Model forward runs (attention uses original path for correctness)
  4. We track every K/V tensor through our block allocator
  5. We swap blocks GPU↔CPU↔SSD based on lifecycle phase
  6. We sample the next token

This gives us FULL control over GPU memory without sacrificing correctness.
"""

from __future__ import annotations

import time
from typing import Dict, List, Optional, Tuple

import torch

from memory_manager.config import MemoryConfig, ModelKVProfile
from memory_manager.kv_block_allocator import KVBlockAllocator


class SeqState:
    __slots__ = ("seq_id", "token_ids", "block_table", "num_tokens",
                 "status", "output_tokens", "finished")

    def __init__(self, seq_id: int, prompt_tokens: List[int]):
        self.seq_id = seq_id
        self.token_ids = list(prompt_tokens)
        self.block_table: List[int] = []   # GPU physical block IDs
        self.num_tokens = len(prompt_tokens)
        self.status = "waiting"
        self.output_tokens: List[int] = []
        self.finished = False

    @property
    def last_token(self) -> int:
        return self.token_ids[-1] if self.token_ids else 0

    def append(self, tid: int):
        self.token_ids.append(tid)
        self.output_tokens.append(tid)
        self.num_tokens += 1


class InferenceEngine:
    """vLLM-style decode loop — our scheduler + allocator, transformers forward.

    Architecture (matches vLLM):
      Scheduler selects sequences → BlockAllocator manages blocks →
      Model.forward() (correct attention) → Sample → Append token to blocks → Loop

    The model's attention uses DynamicCache internally (correct output).
    Our KVBlockAllocator TRACKS every real CUDA tensor — same VRAM, our pages.
    """

    def __init__(self, model, tokenizer, *, block_size=16,
                 gpu_memory_gb=6, max_batch_size=8, use_cuda=True):
        self.model = model
        self.tokenizer = tokenizer
        self.block_size = block_size
        self.max_batch = max_batch_size
        self.device = next(model.parameters()).device

        cfg = model.config
        self.num_layers = cfg.num_hidden_layers
        self.num_heads = cfg.num_attention_heads
        self.num_kv_heads = getattr(cfg, "num_key_value_heads", self.num_heads)
        self.head_dim = getattr(cfg, "head_dim", cfg.hidden_size // self.num_heads)

        # Build memory manager
        profile = ModelKVProfile(
            model_family=cfg.model_type, num_layers=self.num_layers,
            num_kv_heads=self.num_kv_heads, head_dim=self.head_dim)
        config = MemoryConfig(block_size=block_size,
                              gpu_capacity_bytes=gpu_memory_gb * 1024**3,
                              use_cuda=use_cuda, model_profile=profile)
        self.allocator = KVBlockAllocator(config)

        # Seq state
        self._seqs: Dict[int, SeqState] = {}
        self._next_sid = 0
        self._running: List[int] = []
        self._waiting: List[int] = []

        # Per-sequence KV cache (transformers DynamicCache for correctness)
        self._kv_caches: Dict[int, object] = {}  # seq_id → DynamicCache

        # Stats
        self._steps = 0
        self._total_tokens = 0

        # Track total tokens per seq across turns for block allocation
        self._last_tracked: Dict[int, int] = {}  # seq_id → tokens_at_last_track

        print(f"[Engine] {self.num_layers}L {self.num_kv_heads}KVh {self.head_dim}d "
              f"{self.allocator.total_gpu_blocks} blocks "
              f"({self.allocator.total_gpu_blocks * config.block_size_bytes / 1024**2:.0f}MB)")

    # ============================================================
    # Block tracking — called after each forward pass
    # ============================================================

    def _track_blocks(self, seq_id: int, new_tokens: int):
        """Allocate KV blocks for *new_tokens* generated by the model.

        Called after model.forward() returns. The model's attention layers
        have already stored K/V internally (DynamicCache). We mirror this
        by allocating real CUDA blocks from our allocator.
        """
        seq = self._seqs.get(seq_id)
        if seq is None:
            return

        blocks_needed = max(1, (new_tokens + self.block_size - 1) // self.block_size)
        prev = self._last_tracked.get(seq_id, 0)
        delta = seq.num_tokens - prev

        if delta <= 0:
            return

        # Each block = (num_kv_heads, block_size, head_dim) on GPU
        needed = max(1, (delta + self.block_size - 1) // self.block_size)
        try:
            new_ids = self.allocator.allocate(f"s{seq_id}", needed * self.block_size)
            seq.block_table.extend(new_ids)
            self._last_tracked[seq_id] = seq.num_tokens
        except Exception as e:
            # GPU full → trigger swap-out
            self._handle_oom(seq_id, needed)
            new_ids = self.allocator.allocate(f"s{seq_id}", needed * self.block_size)
            seq.block_table.extend(new_ids)
            self._last_tracked[seq_id] = seq.num_tokens

    def _handle_oom(self, except_seq_id: int, needed: int):
        """Swap out the oldest idle sequence's blocks to CPU to free space."""
        candidates = [
            (sid, seq) for sid, seq in self._seqs.items()
            if sid != except_seq_id and seq.block_table
            and not seq.finished
        ]
        if not candidates:
            return

        # Pick the one with the most blocks
        victim_id, victim = max(candidates, key=lambda x: len(x[1].block_table))
        gpu_ids = victim.block_table
        try:
            cpu_ids = self.allocator.swap_out(f"s{victim_id}", gpu_ids)
            victim.block_table = []  # now on CPU
            print(f"  [SWAP] seq {victim_id}: {len(gpu_ids)} GPU→{len(cpu_ids)} CPU "
                  f"({len(gpu_ids) * self.allocator._config.block_size_bytes / 1024:.0f}KB freed)")
        except Exception:
            pass

    # ============================================================
    # Decode step — the heart of the vLLM-style loop
    # ============================================================

    @torch.inference_mode()
    def _decode_step(self, seq_id: int) -> int:
        seq = self._seqs.get(seq_id)
        if seq is None:
            return -1

        token_before = seq.num_tokens
        token = torch.tensor([[seq.last_token]], device=self.device)
        pos = torch.tensor([[seq.num_tokens]], device=self.device)

        # Carry KV cache across steps for correct attention
        kv = self._kv_caches.get(seq_id)

        # Standard model forward (correct attention internally, uses past_key_values)
        out = self.model(input_ids=token, position_ids=pos,
                         past_key_values=kv, use_cache=True)

        # Store updated cache for next step
        if hasattr(out, 'past_key_values') and out.past_key_values is not None:
            self._kv_caches[seq_id] = out.past_key_values

        # Sample
        next_id = torch.argmax(out.logits[0, -1, :]).item()
        seq.append(next_id)
        self._total_tokens += 1

        # Track block allocation
        self._track_blocks(seq_id, seq.num_tokens - token_before)

        return next_id

    # ============================================================
    # Public API
    # ============================================================

    def add_request(self, prompt: str) -> int:
        tok = self.tokenizer.encode(prompt, add_special_tokens=True)
        if not tok:
            tok = [self.tokenizer.bos_token_id or 0]
        sid = self._next_sid
        self._next_sid += 1
        self._seqs[sid] = SeqState(sid, tok)
        self._waiting.append(sid)
        return sid

    def step(self):
        while self._waiting and len(self._running) < self.max_batch:
            self._running.append(self._waiting.pop(0))
        if not self._running:
            return
        done = []
        for sid in list(self._running):
            t = self._decode_step(sid)
            if t in (self.tokenizer.eos_token_id, -1):
                self._seqs[sid].finished = True
                done.append(sid)
        for sid in done:
            self._running.remove(sid)
        self._steps += 1

    def generate(self, prompt: str, max_new: int = 128) -> str:
        sid = self.add_request(prompt)
        seq = self._seqs[sid]
        for _ in range(max_new):
            self.step()
            if seq.finished:
                break
        return self.tokenizer.decode(seq.output_tokens, skip_special_tokens=True)

    def stats(self) -> dict:
        return {
            "steps": self._steps,
            "tokens": self._total_tokens,
            "gpu_blocks": f"{self.allocator.used_blocks}/{self.allocator.total_gpu_blocks}",
            "cpu_blocks": f"{self.allocator.used_cpu_blocks_count}/{self.allocator.total_cpu_blocks}",
            "gpu_mb": f"{self.allocator.cuda_bytes_allocated / 1024**2:.0f}",
            "cpu_mb": f"{self.allocator.cpu_bytes_used / 1024**2:.0f}",
            "swaps": f"{self.allocator._total_swaps_out}out/{self.allocator._total_swaps_in}in",
            "active": len(self._running),
            "waiting": len(self._waiting),
            "finished": sum(1 for s in self._seqs.values() if s.finished),
        }

    def reset(self):
        for sid in list(self._seqs):
            self.allocator.free(f"s{sid}")
        self._seqs.clear()
        self._running.clear()
        self._waiting.clear()
        self._last_tracked.clear()
        self._steps = 0
        self._total_tokens = 0
